# Server Port
spring.application.name=financial-secretary-app
server.port=8080

# 🔄 UPDATED: JWT Security Configuration
finsec.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
finsec.app.jwtExpirationMs=86400000
# (Note: 86400000 ms = 24 hours).

spring.data.mongodb.uri=mongodb://localhost:27017/finsec_db

# Disable Spring Boot Banner
spring.main.banner-mode=off

